image:
  file: .gitpod.Dockerfile

# This will make it so that on workspace start it will run a file called `app.py`
# CodingCoffee  C/C++ GitPod Examples more courses : http://www.codingcoffee.org
tasks:
  - init: echo 'this is linux graphic.h  example' # runs during prebuild
    command: sudo apt update && sudo apt-get install -y build-essential && sudo apt-get install -y libsdl-image1.2 libsdl-image1.2-dev guile-2.0 guile-2.0-dev libsdl1.2debian libart-2.0-dev libaudiofile-dev  libdirectfb-dev libdirectfb-extra libfreetype6-dev libxext-dev x11proto-xext-dev libfreetype6 libaa1 libaa1-dev libslang2-dev libasound2 libasound2-dev libsdl1.2-dev libsdl-image1.2-dev && echo 'this is linux graphic.h  example, please see readme.txt , firstlty'

# CodingCoffee  C/C++ GitPod Examples more courses : http://www.codingcoffee.org
ports:
  - port: 3000
    onOpen: open-preview
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
